services:
  - type: web
    name: revolution-dating
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        generateValue: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
